// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// EMalgorithm_cpp
List EMalgorithm_cpp(const List& x, const arma::mat& y, int max_iter, double eps);
RcppExport SEXP _ZICDT_EMalgorithm_cpp(SEXP xSEXP, SEXP ySEXP, SEXP max_iterSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(EMalgorithm_cpp(x, y, max_iter, eps));
    return rcpp_result_gen;
END_RCPP
}
// getDAGparametersCpppenalty
List getDAGparametersCpppenalty(const arma::mat& G, const List& y_list, double penalty_rate, int em_max_iter, double em_eps, double alpha);
RcppExport SEXP _ZICDT_getDAGparametersCpppenalty(SEXP GSEXP, SEXP y_listSEXP, SEXP penalty_rateSEXP, SEXP em_max_iterSEXP, SEXP em_epsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const List& >::type y_list(y_listSEXP);
    Rcpp::traits::input_parameter< double >::type penalty_rate(penalty_rateSEXP);
    Rcpp::traits::input_parameter< int >::type em_max_iter(em_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type em_eps(em_epsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(getDAGparametersCpppenalty(G, y_list, penalty_rate, em_max_iter, em_eps, alpha));
    return rcpp_result_gen;
END_RCPP
}
// getDAGparametersCpppenalty_cached
List getDAGparametersCpppenalty_cached(const arma::mat& G, const List& y_list, double penalty_rate, int em_max_iter, double em_eps, double alpha);
RcppExport SEXP _ZICDT_getDAGparametersCpppenalty_cached(SEXP GSEXP, SEXP y_listSEXP, SEXP penalty_rateSEXP, SEXP em_max_iterSEXP, SEXP em_epsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const List& >::type y_list(y_listSEXP);
    Rcpp::traits::input_parameter< double >::type penalty_rate(penalty_rateSEXP);
    Rcpp::traits::input_parameter< int >::type em_max_iter(em_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type em_eps(em_epsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(getDAGparametersCpppenalty_cached(G, y_list, penalty_rate, em_max_iter, em_eps, alpha));
    return rcpp_result_gen;
END_RCPP
}
// compute_kl_with_fixed_params_cpp
double compute_kl_with_fixed_params_cpp(const List& test_data_list, const arma::mat& G_fixed, const List& learned_params);
RcppExport SEXP _ZICDT_compute_kl_with_fixed_params_cpp(SEXP test_data_listSEXP, SEXP G_fixedSEXP, SEXP learned_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type test_data_list(test_data_listSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G_fixed(G_fixedSEXP);
    Rcpp::traits::input_parameter< const List& >::type learned_params(learned_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_kl_with_fixed_params_cpp(test_data_list, G_fixed, learned_params));
    return rcpp_result_gen;
END_RCPP
}
// compute_node_marginal_cost_cpp
double compute_node_marginal_cost_cpp(int node_idx, int parent_idx, const List& y_list, double penalty_rate, double alpha, int em_max_iter, double em_eps);
RcppExport SEXP _ZICDT_compute_node_marginal_cost_cpp(SEXP node_idxSEXP, SEXP parent_idxSEXP, SEXP y_listSEXP, SEXP penalty_rateSEXP, SEXP alphaSEXP, SEXP em_max_iterSEXP, SEXP em_epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type node_idx(node_idxSEXP);
    Rcpp::traits::input_parameter< int >::type parent_idx(parent_idxSEXP);
    Rcpp::traits::input_parameter< const List& >::type y_list(y_listSEXP);
    Rcpp::traits::input_parameter< double >::type penalty_rate(penalty_rateSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type em_max_iter(em_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type em_eps(em_epsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_node_marginal_cost_cpp(node_idx, parent_idx, y_list, penalty_rate, alpha, em_max_iter, em_eps));
    return rcpp_result_gen;
END_RCPP
}
// clear_node_cache
void clear_node_cache();
RcppExport SEXP _ZICDT_clear_node_cache() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    clear_node_cache();
    return R_NilValue;
END_RCPP
}
// get_cache_size
int get_cache_size();
RcppExport SEXP _ZICDT_get_cache_size() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_cache_size());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ZICDT_EMalgorithm_cpp", (DL_FUNC) &_ZICDT_EMalgorithm_cpp, 4},
    {"_ZICDT_getDAGparametersCpppenalty", (DL_FUNC) &_ZICDT_getDAGparametersCpppenalty, 6},
    {"_ZICDT_getDAGparametersCpppenalty_cached", (DL_FUNC) &_ZICDT_getDAGparametersCpppenalty_cached, 6},
    {"_ZICDT_compute_kl_with_fixed_params_cpp", (DL_FUNC) &_ZICDT_compute_kl_with_fixed_params_cpp, 3},
    {"_ZICDT_compute_node_marginal_cost_cpp", (DL_FUNC) &_ZICDT_compute_node_marginal_cost_cpp, 7},
    {"_ZICDT_clear_node_cache", (DL_FUNC) &_ZICDT_clear_node_cache, 0},
    {"_ZICDT_get_cache_size", (DL_FUNC) &_ZICDT_get_cache_size, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ZICDT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
