# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EMalgorithm_cpp <- function(x, y, max_iter = 5000L, eps = 1e-6) {
    .Call(`_ZICDT_EMalgorithm_cpp`, x, y, max_iter, eps)
}

getDAGparametersCpppenalty <- function(G, y_list, penalty_rate = 1.0, em_max_iter = 5000L, em_eps = 1e-6, alpha = 1.0) {
    .Call(`_ZICDT_getDAGparametersCpppenalty`, G, y_list, penalty_rate, em_max_iter, em_eps, alpha)
}

getDAGparametersCpppenalty_cached <- function(G, y_list, penalty_rate = 1.0, em_max_iter = 5000L, em_eps = 1e-6, alpha = 1.0) {
    .Call(`_ZICDT_getDAGparametersCpppenalty_cached`, G, y_list, penalty_rate, em_max_iter, em_eps, alpha)
}

compute_kl_with_fixed_params_cpp <- function(test_data_list, G_fixed, learned_params) {
    .Call(`_ZICDT_compute_kl_with_fixed_params_cpp`, test_data_list, G_fixed, learned_params)
}

compute_node_marginal_cost_cpp <- function(node_idx, parent_idx, y_list, penalty_rate, alpha, em_max_iter, em_eps) {
    .Call(`_ZICDT_compute_node_marginal_cost_cpp`, node_idx, parent_idx, y_list, penalty_rate, alpha, em_max_iter, em_eps)
}

clear_node_cache <- function() {
    invisible(.Call(`_ZICDT_clear_node_cache`))
}

get_cache_size <- function() {
    .Call(`_ZICDT_get_cache_size`)
}

